/**
 * TreeGrid DataSource
 */

let id = 0;

const genTaskId = () => {
  return ++id;
};

const data = [];

while (id < 1000) {
  data.push({
    taskID: genTaskId(),
    taskName: "Planning",
    startDate: new Date("02/03/2017"),
    endDate: new Date("02/07/2017"),
    progress: 100,
    duration: 5,
    priority: "Normal",
    approved: false,
    subtasks: [
      {
        taskID: genTaskId(),
        taskName: "Plan timeline",
        startDate: new Date("02/03/2017"),
        endDate: new Date("02/07/2017"),
        duration: 5,
        progress: 100,
        priority: "Normal",
        approved: false,
      },
      {
        taskID: genTaskId(),
        taskName: "Plan budget",
        startDate: new Date("02/03/2017"),
        endDate: new Date("02/07/2017"),
        duration: 5,
        progress: 100,
        priority: "Low",
        approved: true,
      },
      {
        taskID: genTaskId(),
        taskName: "Allocate resources",
        startDate: new Date("02/03/2017"),
        endDate: new Date("02/07/2017"),
        duration: 5,
        progress: 100,
        priority: "Critical",
        approved: false,
      },
      {
        taskID: genTaskId(),
        taskName: "Planning complete",
        startDate: new Date("02/07/2017"),
        endDate: new Date("02/07/2017"),
        duration: 0,
        progress: 0,
        priority: "Low",
        approved: true,
      },
    ],
  },
  {
    taskID: genTaskId(),
    taskName: "Design",
    startDate: new Date("02/10/2017"),
    endDate: new Date("02/14/2017"),
    duration: 3,
    progress: 86,
    priority: "High",
    approved: false,
    subtasks: [
      {
        taskID: genTaskId(),
        taskName: "Software Specification",
        startDate: new Date("02/10/2017"),
        endDate: new Date("02/12/2017"),
        duration: 3,
        progress: 60,
        priority: "Normal",
        approved: false,
      },
      {
        taskID: genTaskId(),
        taskName: "Develop prototype",
        startDate: new Date("02/10/2017"),
        endDate: new Date("02/12/2017"),
        duration: 3,
        progress: 100,
        priority: "Critical",
        approved: false,
      },
      {
        taskID: genTaskId(),
        taskName: "Get approval from customer",
        startDate: new Date("02/13/2017"),
        endDate: new Date("02/14/2017"),
        duration: 2,
        progress: 100,
        priority: "Low",
        approved: true,
      },
      {
        taskID: genTaskId(),
        taskName: "Design Documentation",
        startDate: new Date("02/13/2017"),
        endDate: new Date("02/14/2017"),
        duration: 2,
        progress: 100,
        priority: "High",
        approved: true,
      },
      {
        taskID: genTaskId(),
        taskName: "Design complete",
        startDate: new Date("02/14/2017"),
        endDate: new Date("02/14/2017"),
        duration: 0,
        progress: 0,
        priority: "Normal",
        approved: true,
      },
    ],
  },
  {
    taskID: genTaskId(),
    taskName: "Implementation Phase",
    startDate: new Date("02/17/2017"),
    endDate: new Date("02/27/2017"),
    priority: "Normal",
    approved: false,
    duration: 11,
    progress: 66,
    subtasks: [
      {
        taskID: genTaskId(),
        taskName: "Phase 1",
        startDate: new Date("02/17/2017"),
        endDate: new Date("02/27/2017"),
        priority: "High",
        approved: false,
        progress: 50,
        duration: 11,
        subtasks: [
          {
            taskID: genTaskId(),
            taskName: "Implementation Module 1",
            startDate: new Date("02/17/2017"),
            endDate: new Date("02/27/2017"),
            priority: "Normal",
            duration: 11,
            progress: 10,
            approved: false,
            subtasks: [
              {
                taskID: genTaskId(),
                taskName: "Development Task 1",
                startDate: new Date("02/17/2017"),
                endDate: new Date("02/19/2017"),
                duration: 3,
                progress: "50",
                priority: "High",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Development Task 2",
                startDate: new Date("02/17/2017"),
                endDate: new Date("02/19/2017"),
                duration: 3,
                progress: "50",
                priority: "Low",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Testing",
                startDate: new Date("02/20/2017"),
                endDate: new Date("02/21/2017"),
                duration: 2,
                progress: "0",
                priority: "Normal",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Bug fix",
                startDate: new Date("02/24/2017"),
                endDate: new Date("02/25/2017"),
                duration: 2,
                progress: "0",
                priority: "Critical",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Customer review meeting",
                startDate: new Date("02/26/2017"),
                endDate: new Date("02/27/2017"),
                duration: 2,
                progress: "0",
                priority: "High",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Phase 1 complete",
                startDate: new Date("02/27/2017"),
                endDate: new Date("02/27/2017"),
                duration: 0,
                progress: "50",
                priority: "Low",
                approved: true,
              },
            ],
          },
        ],
      },
      {
        taskID: genTaskId(),
        taskName: "Phase 2",
        startDate: new Date("02/17/2017"),
        endDate: new Date("02/28/2017"),
        priority: "High",
        approved: false,
        duration: 12,
        progress: 60,
        subtasks: [
          {
            taskID: genTaskId(),
            taskName: "Implementation Module 2",
            startDate: new Date("02/17/2017"),
            endDate: new Date("02/28/2017"),
            priority: "Critical",
            approved: false,
            duration: 12,
            progress: 90,
            subtasks: [
              {
                taskID: genTaskId(),
                taskName: "Development Task 1",
                startDate: new Date("02/17/2017"),
                endDate: new Date("02/20/2017"),
                duration: 4,
                progress: "50",
                priority: "Normal",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Development Task 2",
                startDate: new Date("02/17/2017"),
                endDate: new Date("02/20/2017"),
                duration: 4,
                progress: "50",
                priority: "Critical",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Testing",
                startDate: new Date("02/21/2017"),
                endDate: new Date("02/24/2017"),
                duration: 2,
                progress: "0",
                priority: "High",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Bug fix",
                startDate: new Date("02/25/2017"),
                endDate: new Date("02/26/2017"),
                duration: 2,
                progress: "0",
                priority: "Low",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Customer review meeting",
                startDate: new Date("02/27/2017"),
                endDate: new Date("02/28/2017"),
                duration: 2,
                progress: "0",
                priority: "Critical",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Phase 2 complete",
                startDate: new Date("02/28/2017"),
                endDate: new Date("02/28/2017"),
                duration: 0,
                progress: "50",
                priority: "Normal",
                approved: false,
              },
            ],
          },
        ],
      },
      {
        taskID: genTaskId(),
        taskName: "Phase 3",
        startDate: new Date("02/17/2017"),
        endDate: new Date("02/27/2017"),
        priority: "Normal",
        approved: false,
        duration: 11,
        progress: 30,
        subtasks: [
          {
            taskID: genTaskId(),
            taskName: "Implementation Module 3",
            startDate: new Date("02/17/2017"),
            endDate: new Date("02/27/2017"),
            priority: "High",
            approved: false,
            duration: 11,
            progress: 60,
            subtasks: [
              {
                taskID: genTaskId(),
                taskName: "Development Task 1",
                startDate: new Date("02/17/2017"),
                endDate: new Date("02/19/2017"),
                duration: 3,
                progress: "50",
                priority: "Low",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Development Task 2",
                startDate: new Date("02/17/2017"),
                endDate: new Date("02/19/2017"),
                duration: 3,
                progress: "50",
                priority: "Normal",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Testing",
                startDate: new Date("02/20/2017"),
                endDate: new Date("02/21/2017"),
                duration: 2,
                progress: "0",
                priority: "Critical",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Bug fix",
                startDate: new Date("02/24/2017"),
                endDate: new Date("02/25/2017"),
                duration: 2,
                progress: "0",
                priority: "High",
                approved: false,
              },
              {
                taskID: genTaskId(),
                taskName: "Customer review meeting",
                startDate: new Date("02/26/2017"),
                endDate: new Date("02/27/2017"),
                duration: 2,
                progress: "0",
                priority: "Normal",
                approved: true,
              },
              {
                taskID: genTaskId(),
                taskName: "Phase 3 complete",
                startDate: new Date("02/27/2017"),
                endDate: new Date("02/27/2017"),
                duration: 0,
                progress: "50",
                priority: "Critical",
                approved: false,
              },
            ],
          },
        ],
      },
      {
        taskID: genTaskId(),
        taskName: "Implementation Phase",
        startDate: new Date("05/11/2017"),
        endDate: new Date("05/21/2017"),
        priority: "High",
        approved: false,
        duration: 17,
        progress: 80,
        subtasks: [
          {
            taskID: genTaskId(),
            taskName: "Phase 1",
            startDate: new Date("05/11/2017"),
            endDate: new Date("05/21/2017"),
            priority: "High",
            approved: false,
            progress: 50,
            duration: 11,
            subtasks: [
              {
                taskID: genTaskId(),
                taskName: "Implementation Module 1",
                startDate: new Date("05/11/2017"),
                endDate: new Date("05/21/2017"),
                priority: "Normal",
                duration: 11,
                progress: 10,
                approved: false,
                subtasks: [
                  {
                    taskID: genTaskId(),
                    taskName: "Development Task 1",
                    startDate: new Date("05/13/2017"),
                    endDate: new Date("05/14/2017"),
                    duration: 3,
                    progress: "50",
                    priority: "High",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Development Task 2",
                    startDate: new Date("05/13/2017"),
                    endDate: new Date("05/14/2017"),
                    duration: 3,
                    progress: "50",
                    priority: "Low",
                    approved: true,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Testing",
                    startDate: new Date("05/15/2017"),
                    endDate: new Date("05/17/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "Normal",
                    approved: true,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Bug fix",
                    startDate: new Date("05/18/2017"),
                    endDate: new Date("05/19/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "Critical",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Customer review meeting",
                    startDate: new Date("05/20/2017"),
                    endDate: new Date("05/20/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "High",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Phase 1 complete",
                    startDate: new Date("05/21/2017"),
                    endDate: new Date("05/21/2017"),
                    duration: 0,
                    progress: "50",
                    priority: "Low",
                    approved: true,
                  },
                ],
              },
            ],
          },
          {
            taskID: genTaskId(),
            taskName: "Phase 2",
            startDate: new Date("06/11/2017"),
            endDate: new Date("06/21/2017"),
            priority: "High",
            approved: false,
            duration: 19,
            progress: 56,
            subtasks: [
              {
                taskID: genTaskId(),
                taskName: "Implementation Module 2",
                startDate: new Date("06/11/2017"),
                endDate: new Date("06/21/2017"),
                priority: "Critical",
                approved: false,
                duration: 15,
                progress: 95,
                subtasks: [
                  {
                    taskID: genTaskId(),
                    taskName: "Development Task 1",
                    startDate: new Date("06/13/2017"),
                    endDate: new Date("06/14/2017"),
                    duration: 3,
                    progress: "50",
                    priority: "High",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Development Task 2",
                    startDate: new Date("06/13/2017"),
                    endDate: new Date("06/14/2017"),
                    duration: 3,
                    progress: "50",
                    priority: "Low",
                    approved: true,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Testing",
                    startDate: new Date("06/15/2017"),
                    endDate: new Date("06/17/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "Normal",
                    approved: true,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Bug fix",
                    startDate: new Date("06/18/2017"),
                    endDate: new Date("06/19/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "Critical",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Customer review meeting",
                    startDate: new Date("06/20/2017"),
                    endDate: new Date("06/20/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "High",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Phase 1 complete",
                    startDate: new Date("06/21/2017"),
                    endDate: new Date("06/21/2017"),
                    duration: 0,
                    progress: "50",
                    priority: "Low",
                    approved: true,
                  },
                ],
              },
            ],
          },
          {
            taskID: genTaskId(),
            taskName: "Phase 3",
            startDate: new Date("07/11/2017"),
            endDate: new Date("07/21/2017"),
            priority: "Normal",
            approved: false,
            duration: 11,
            progress: 30,
            subtasks: [
              {
                taskID: genTaskId(),
                taskName: "Implementation Module 3",
                startDate: new Date("07/11/2017"),
                endDate: new Date("07/21/2017"),
                priority: "High",
                approved: false,
                duration: 11,
                progress: 60,
                subtasks: [
                  {
                    taskID: genTaskId(),
                    taskName: "Development Task 1",
                    startDate: new Date("07/13/2017"),
                    endDate: new Date("07/14/2017"),
                    duration: 3,
                    progress: "50",
                    priority: "High",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Development Task 2",
                    startDate: new Date("07/13/2017"),
                    endDate: new Date("07/14/2017"),
                    duration: 3,
                    progress: "50",
                    priority: "Low",
                    approved: true,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Testing",
                    startDate: new Date("07/15/2017"),
                    endDate: new Date("07/17/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "Normal",
                    approved: true,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Bug fix",
                    startDate: new Date("07/18/2017"),
                    endDate: new Date("07/19/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "Critical",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Customer review meeting",
                    startDate: new Date("07/20/2017"),
                    endDate: new Date("07/20/2017"),
                    duration: 2,
                    progress: "0",
                    priority: "High",
                    approved: false,
                  },
                  {
                    taskID: genTaskId(),
                    taskName: "Phase 1 complete",
                    startDate: new Date("07/21/2017"),
                    endDate: new Date("07/21/2017"),
                    duration: 0,
                    progress: "50",
                    priority: "Low",
                    approved: true,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  });
}

exports.sampleData = data;
